import { mkdirSync, writeFileSync, cpSync } from 'node:fs';
import { resolve } from 'node:path';
import { site as s, faq } from './site.mjs';

const out = resolve(import.meta.dirname, '../dist');
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if (!s.staging && (s.phoneLink === '+420123456789' || s.businessId === '111111111' || s.businessName === 'DUKE test')) throw new Error('Před ostrým režimem doplňte skutečný telefon a firemní údaje.');
mkdirSync(out, { recursive: true });
cpSync(resolve(import.meta.dirname, '../public'), out, { recursive: true });
const pages = [
  ['', 'Úvod', 'Masáže Vsetín | Lucie Krampotová – 22 let praxe', 'Masáže zad a šíje ve Vsetíně. Lucie Krampotová, 22 let praxe, individuální přístup. Mostecká 361. Objednání telefonem nebo SMS.'],
  ['masaze', 'Masáže', 'Masáž zad a šíje Vsetín | Lucie Krampotová', 'Cílená 30minutová masáž zad a šíje nebo 60 minut individuální péče ve Vsetíně. Domluvte si masáž telefonicky nebo SMS.'],
  ['o-lucii', 'O Lucii', 'O Lucii Krampotové | Masáže Vsetín, 22 let praxe', 'Poznejte přístup Lucie Krampotové k masážím zad. 22 let praxe, individuální péče a odborný přesah vzdělávání v DNS.'],
  ['cenik', 'Ceník', 'Ceník masáží Vsetín | Lucie Krampotová', 'Masáže v délce 30 a 60 minut. Ceny připravujeme a upřesníme je při objednání. Mostecká 361, Vsetín.'],
  ['darkove-poukazy', 'Dárkové poukazy', 'Dárkové poukazy na masáž Vsetín | Lucie Krampotová', 'Darujte čas na odpočinek. Dárkové poukazy na 30 nebo 60 minut masáže ve Vsetíně. Objednání telefonicky nebo SMS.'],
  ['reference', 'Reference', 'Reference | Lucie Krampotová, masáže Vsetín', 'Prostor pro skutečné zkušenosti klientů Lucie Krampotové. Recenze zatím nejsou zveřejněné.'],
  ['faq', 'FAQ', 'Časté otázky k masážím | Lucie Krampotová Vsetín', 'Jak se objednat na masáž, jak vybrat délku a jak domluvit dárkový poukaz. Odpovědi na časté otázky.'],
  ['kontakt', 'Kontakt', 'Kontakt a mapa | Masáže Vsetín, Mostecká 361', 'Lucie Krampotová, masáže zad a šíje. Mostecká 361, Vsetín. Dle objednání, telefon nebo SMS 123 456 789.'],
  ['soukromi', 'Soukromí', 'Informace o webu a soukromí | Lucie Krampotová', 'Informace o testovací verzi webu, kontaktních údajích a načítání mapy.']
];
function render(route, label, title, description, notFound = false) {
  const base = notFound ? '/' : route ? '../' : './';
  const link = path => `${base}${path ? path + '/' : ''}`;
  const call = (text = 'Domluvit masáž', cls = 'button') => `<a class="${cls}" href="tel:${s.phoneLink}">${text}<span aria-hidden="true">↗</span></a>`;
  const sms = (text = 'Napsat SMS', subject = '') => `<a class="button secondary" href="sms:${s.phoneLink}${subject ? '?body=' + encodeURIComponent(subject) : ''}">${text}<span aria-hidden="true">↗</span></a>`;
  const eyebrow = text => `<p class="eyebrow">${text}</p>`;
  const pageHero = (tag, heading, copy) => `<section class="page-hero wrap">${eyebrow(tag)}<h1>${heading}</h1><p class="lead">${copy}</p></section>`;
  const faqList = (items = faq) => `<div class="faq-list">${items.map(([q,a],i) => `<details><summary><span class="question-number">${String(i+1).padStart(2,'0')}</span><span>${q}</span><span class="plus" aria-hidden="true"></span></summary><p>${a}</p></details>`).join('')}</div>`;
  const cards = () => `<div class="service-grid">${s.services.map((x,i) => `<article class="service-card"><div class="service-top"><span class="eyebrow">0${i+1}</span><span class="duration">${x.minutes}<small>minut pro vás</small></span></div><div class="service-description"><h3>${x.name}</h3><p>${x.description}</p></div><div class="service-bottom"><div class="price">${esc(x.price)}<span>cenu upřesníme při objednání</span></div><a href="${link('masaze')}#masaz-${x.minutes}" aria-label="Více o masáži na ${x.minutes} minut" class="circle-link">↗</a></div></article>`).join('')}</div>`;
  const cta = () => `<section class="cta"><div class="wrap cta-inner"><div>${eyebrow('VÁŠ ČAS ZAČÍNÁ DOMLUVOU')}<h2>Dopřejte zádům<br><em>chvíli pozornosti.</em></h2></div><div><p>Vybereme společně termín i délku masáže.</p><div class="actions">${call('Zavolat Lucii')}${sms()}</div><p class="small">${s.phone} · Návštěvy dle objednání</p></div></div></section>`;
  const map = () => `<div class="map-panel" data-map-panel><span class="map-marker" aria-hidden="true">↗</span><h3>Najdete mě ve Vsetíně.</h3><p>${s.address}<br>${s.city}</p><button class="button secondary" type="button" data-load-map>Zobrazit mapu<span aria-hidden="true">+</span></button><p class="small">Kliknutím se načte mapa od Google.</p><a class="text-link" href="https://www.google.com/maps/search/?api=1&amp;query=Mosteck%C3%A1%20361%2C%20Vset%C3%ADn" target="_blank" rel="noopener noreferrer">Otevřít trasu v Mapách Google ↗</a></div>`;
  let body = '';
  if (notFound) body = pageHero('404 / STRÁNKA NENALEZENA','Tady si dáme<br><em>malou pauzu.</em>','Tato stránka tu není. Vše o masážích a objednání najdete na úvodní stránce.') + `<div class="wrap section-bottom"><a class="button" href="${link('')}">Zpět na úvod ↗</a></div>`;
  else if (!route) body = `
    <section class="hero"><figure class="hero-image"><img src="${base}assets/wellness.webp" srcset="${base}assets/wellness-small.webp 640w, ${base}assets/wellness.webp 1280w" sizes="(max-width: 760px) 100vw, 65vw" alt="Krémové ručníky a masážní olej v teplém světle – ilustrační zátiší" width="1280" height="1600" fetchpriority="high"><figcaption>Ilustrační fotografie</figcaption></figure><div class="wrap hero-content"><div class="hero-copy">${eyebrow('MASÁŽE ZAD A ŠÍJE · VSETÍN')}<h1>Čas pro vás.<br><em>Péče pro<br>vaše záda.</em></h1><p class="lead">Odložte na chvíli každodenní shon.<br>Dopřejte si masáž s osobním přístupem<br>a 22 lety zkušeností.</p><div class="actions">${call('Domluvit si masáž')}<a class="text-link" href="${link('masaze')}">Prohlédnout masáže <span aria-hidden="true">↗</span></a></div></div><div class="hero-foot"><span>MOSTECKÁ 361 · VSETÍN</span><a href="#masaze">CHVÍLE KLIDU ZAČÍNÁ TADY <span aria-hidden="true">↓</span></a></div></div></section>
    <div class="values-line"><div class="wrap"><span><strong>22</strong> let praxe</span><span><strong>30 / 60</strong> minut péče</span><span><strong>DNS</strong> odborný přesah</span><span><strong>Vy</strong> na prvním místě</span></div></div>
    <section class="light section services-section" id="masaze"><div class="wrap"><div class="section-heading"><div>${eyebrow('PÉČE PŘESNĚ PRO VÁS')}<h2>Vaše záda.<br><em>V dobrých rukou.</em></h2></div><p>Po dni u počítače, fyzické práci i sportu. Vyberte si čas, který dnes potřebujete. Vše ostatní si domluvíme společně.</p></div>${cards()}<div class="under-cards"><span>Délku i intenzitu přizpůsobíme vám.</span><a class="text-link" href="${link('cenik')}">Kompletní ceník ↗</a></div></div></section>
    <section class="section about-section"><div class="wrap about-home"><div class="experience-panel">${eyebrow('ZKUŠENOST A POZORNOST')}<div class="big-number">${s.years}<span>let praxe</span></div><p>Protože každá záda<br>mají svůj příběh.</p></div><div>${eyebrow('LUCIE KRAMPOTOVÁ')}<h2>Osobně.<br>Pozorně.<br><em>S respektem k vám.</em></h2><p class="lead">Za každou masáží je člověk. A pro mě je důležité věnovat se právě tomu, co potřebujete vy.</p><p>Masážím se věnuji už 22 let. Mou praxi doplňuje vzdělávání v DNS, ale základem každé návštěvy zůstává domluva a péče přizpůsobená vašemu tělu.</p><a class="text-link" href="${link('o-lucii')}">Poznejte můj přístup ↗</a></div></div></section>
    <section class="gift-section"><div class="wrap gift-inner"><div>${eyebrow('DÁRKOVÉ POUKAZY')}<h2>Ten nejhezčí dárek?<br><em>Chvíle jen pro sebe.</em></h2></div><div><p>Darujte někomu blízkému 30 nebo 60 minut odpočinku a individuální péče.</p><a class="button" href="${link('darkove-poukazy')}">Darovat masáž <span aria-hidden="true">↗</span></a></div></div></section>
    <section class="wrap references-home"><div>${eyebrow('SKUTEČNÉ ZKUŠENOSTI')}<h2>Vaše slova <em>mají své místo.</em></h2></div><div><p>Zatím zde nejsou zveřejněné žádné recenze. Patřit sem budou pouze skutečná hodnocení klientů.</p><a class="text-link" href="${link('reference')}">Reference ↗</a></div></section>
    <section class="light section"><div class="wrap faq-grid"><div>${eyebrow('05 / ČASTÉ OTÁZKY')}<h2>Ať přicházíte<br><em>v klidu.</em></h2><a class="text-link" href="${link('faq')}">Všechny otázky ↗</a></div>${faqList(faq.slice(0,4))}</div></section>
    <section class="section wrap contact-grid"><div>${eyebrow('06 / KONTAKT')}<h2>Vaše zastavení<br><em>ve Vsetíně.</em></h2><p class="lead">${s.address}<br>${s.city}</p><p>Návštěvy dle objednání.<br>Termín domluvíme telefonem nebo SMS.</p><a class="phone-link" href="tel:${s.phoneLink}">${s.phone}</a><div class="actions">${sms()}<a class="text-link" href="${link('kontakt')}">Kontaktní informace ↗</a></div></div>${map()}</section>`;
  else if (route === 'masaze') body = pageHero('MASÁŽE ZAD A ŠÍJE · VSETÍN','Péče podle toho,<br><em>co potřebujete.</em>','Každý den dává vašim zádům zabrat jinak. Délku, zaměření i intenzitu masáže si společně domluvíme.') + `<section class="light section"><div class="wrap">${s.services.map((x,i)=>`<article id="masaz-${x.minutes}" class="service-detail"><div>${eyebrow('0'+(i+1)+' / '+x.minutes+' MINUT')}<h2>${x.name}</h2></div><div><p class="lead">${x.description}</p><p>${i ? 'Delší návštěva dává prostor věnovat se jednotlivým partiím postupně a bez spěchu. Konkrétní rozsah si určíme po úvodní domluvě.' : 'Kratší návštěva soustředěná na oblast zad a šíje. Zaměření domluvíme podle toho, které partie si zaslouží nejvíce pozornosti.'}</p><div class="detail-price">${esc(x.price)} <span>/ ${x.minutes} minut</span></div>${call('Domluvit '+x.minutes+' minut')}</div></article>`).join('')}</div></section><section class="section wrap"><div class="section-heading"><div>${eyebrow('PRŮBĚH NÁVŠTĚVY')}<h2>Od domluvy<br><em>k odpočinku.</em></h2></div></div><div class="steps"><article><span>01</span><h3>Krátce si promluvíme</h3><p>Řeknete mi, co od masáže očekáváte a čemu chcete věnovat pozornost.</p></article><article><span>02</span><h3>Přizpůsobíme péči</h3><p>Společně domluvíme partie i intenzitu. Vaše pohodlí je součástí každé masáže.</p></article><article><span>03</span><h3>Čas je jen váš</h3><p>Prostor pro klid a odpočinek. Pokud cokoli potřebujete změnit, stačí říct.</p></article></div></section>${cta()}`;
  else if (route === 'o-lucii') body = pageHero('O LUCII','Zkušenost v rukou.<br><em>Pozornost k člověku.</em>','Jsem Lucie Krampotová. Už 22 let se věnuji masážím a péči o namáhaná záda.') + `<section class="light section"><div class="wrap editorial"><h2>Každý člověk<br>přichází <em>s jiným dnem.</em></h2><div><p class="lead">Někdo celý den seděl. Jiný pracoval rukama, sportoval nebo si zkrátka potřebuje dopřát chvíli klidu.</p><p>Proto je pro mě důležitá osobní domluva. Zajímá mě, kterým partiím chcete věnovat pozornost a jaká intenzita je vám příjemná. Masáž přizpůsobuji vám.</p><p>Najdete mě na Mostecké 361 ve Vsetíně. Návštěvy probíhají dle předchozího objednání, abych na vás měla vyhrazený čas.</p></div></div></section><section class="section wrap editorial"><div>${eyebrow('ODBORNÝ PŘESAH')}<h2>Praxe a vzdělávání<br><em>patří k sobě.</em></h2></div><div><p class="lead">Součástí mého vzdělávání je také DNS – dynamická neuromuskulární stabilizace.</p><p>Tento odborný přesah doplňuje mou masérskou praxi. Nabízenou službou je masáž; nejedná se o fyzioterapii ani lékařskou péči.</p><p class="muted">Přesné názvy absolvovaných kurzů a podklady ke vzdělání zde doplníme po jejich ověření.</p></div></section>${cta()}`;
  else if (route === 'cenik') body = pageHero('CENÍK','Vyberte si<br><em>svůj čas.</em>','Dvě délky návštěvy, stejná osobní pozornost. Ceny právě připravujeme a upřesníme je před potvrzením vašeho termínu.') + `<section class="light section"><div class="wrap pricing-table">${s.services.map(x=>`<article><span class="duration">${x.minutes}<small>minut</small></span><div><h2>${x.name}</h2><p>${x.description}</p></div><strong>${esc(x.price)}</strong></article>`).join('')}<p>Cenu i podrobnosti domluvíme při objednání. Způsob platby vám potvrdíme před návštěvou.</p></div></section>${cta()}`;
  else if (route === 'darkove-poukazy') body = pageHero('DÁRKOVÉ POUKAZY','Malé gesto.<br><em>Velký prostor pro sebe.</em>','Darujte masáž někomu, kdo si zaslouží na chvíli vypnout. Osobní dárek pro ženy i muže.') + `<section class="light section"><div class="wrap editorial"><div><h2>30 nebo 60 minut.<br><em>Radost podle vás.</em></h2><p>Poukaz lze domluvit na kratší masáž zad a šíje i na delší individuální péči.</p></div><div class="gift-options"><h3>Jak poukaz objednat</h3><ol><li>Zavolejte nebo napište SMS s požadovanou délkou masáže.</li><li>Domluvíme cenu, podobu, způsob předání a platnost poukazu.</li><li>Obdarovaný si následně objedná svůj termín telefonem nebo SMS.</li></ol><div class="actions">${call('Domluvit poukaz')}${sms('Poptat poukaz SMS','Dobrý den, mám zájem o dárkový poukaz na masáž. Prosím o informace.')} </div><p class="small">Cena a podmínky budou potvrzeny před objednáním.</p></div></div></section>`;
  else if (route === 'reference') body = pageHero('REFERENCE','Důvěra vyrůstá<br><em>ze skutečné zkušenosti.</em>','Místo pro hodnocení lidí, kteří masáž osobně zažili.') + `<section class="light section"><div class="wrap empty-reviews"><span class="empty-mark" aria-hidden="true">„</span><h2>Každá zkušenost<br><em>má svůj příběh.</em></h2><p>Zatím zde nejsou zveřejněné žádné recenze.</p><p>Až budou k dispozici skutečná hodnocení a souhlas s jejich zveřejněním, najdete je zde. Do té doby se můžete seznámit s mým přístupem k masážím.</p><a class="text-link" href="${link('o-lucii')}">Více o Lucii ↗</a></div></section>${cta()}`;
  else if (route === 'faq') body = pageHero('ČASTÉ OTÁZKY','Dobré vědět.<br><em>Ještě než přijdete.</em>','Od první objednávky po dárkový poukaz. Tady najdete odpovědi na to nejdůležitější.') + `<section class="light section"><div class="wrap narrow">${faqList()}</div></section>${cta()}`;
  else if (route === 'kontakt') body = pageHero('KONTAKT · VSETÍN','Ozvěte se.<br><em>Najdeme váš termín.</em>','Objednání je osobní a jednoduché. Stačí zavolat nebo poslat SMS.') + `<section class="light section"><div class="wrap contact-grid"><div><h2>Lucie Krampotová</h2><p>Masáže zad a šíje</p><a class="phone-link dark" href="tel:${s.phoneLink}">${s.phone}</a><div class="actions">${call('Zavolat')}${sms()}</div><dl class="contact-details"><div><dt>ADRESA</dt><dd>${s.address}, ${s.city}</dd></div><div><dt>NÁVŠTĚVY</dt><dd>Dle předchozího objednání</dd></div></dl><p>Do SMS napište své jméno, požadovanou délku masáže a termín, který vám vyhovuje. Vyčkejte prosím na potvrzení.</p></div>${map()}</div></section><section class="wrap section business-details">${eyebrow('ÚDAJE PROVOZOVATELE')}<h2>${s.businessName}</h2><p>IČO: ${s.businessId}</p><p class="muted">Dočasné testovací údaje. Skutečné údaje provozovatele a kontaktní telefon doplníme před ostrým spuštěním.</p></section>`;
  else body = pageHero('INFORMACE O WEBU','Soukromí<br><em>a testovací provoz.</em>','Přehled toho, jak je tato verze webu připravena.') + `<section class="light section"><div class="wrap narrow prose"><h2>Testovací údaje</h2><p>Tento web je testovací prezentací na lucie.jede.online. Telefon ${s.phone}, název ${s.businessName} a IČO ${s.businessId} jsou dočasné údaje, které musí být před ostrým spuštěním nahrazeny.</p><h2>Bez formuláře a analytiky</h2><p>Web nemá objednávkový formulář, nenastavuje analytické ani reklamní cookies a nepoužívá měřicí nástroje. Telefonní a SMS odkazy otevírají odpovídající aplikaci ve vašem zařízení.</p><h2>Externí mapa</h2><p>Mapa Google se načítá pouze po kliknutí na „Zobrazit mapu“. Při načtení se prohlížeč spojí se službou Google, která získá běžné technické údaje o připojení, například IP adresu. Alternativně můžete otevřít adresu přímo v Mapách Google.</p><h2>Objednávky a hosting</h2><p>Při skutečných objednávkách bude provozovatel zpracovávat údaje nezbytné pro domluvu návštěvy. Úplné informace o správci, zpracování objednávek a případných serverových záznamech doplníme podle skutečného provozovatele a zvoleného hostingu před ostrým spuštěním.</p><h2>Fotografie</h2><p>Použité zátiší je vytvořená ilustrační fotografie. Nezobrazuje skutečnou provozovnu.</p></div></section>`;
  const canonical = `${s.origin}/${route && !notFound ? route+'/' : ''}`;
  const schema = {'@context':'https://schema.org','@graph':[
    {'@type':'LocalBusiness','@id':s.origin+'/#business',name:s.name,description:'Masáže zad a šíje ve Vsetíně. 22 let praxe.',url:s.origin+'/',telephone:s.phoneLink,address:{'@type':'PostalAddress',streetAddress:s.address,addressLocality:s.city,addressCountry:'CZ'},areaServed:{'@type':'City',name:s.city},image:s.origin+'/assets/wellness.webp'},
    {'@type':'WebSite','@id':s.origin+'/#website',url:s.origin+'/',name:'Lucie Krampotová – Masáže Vsetín',inLanguage:'cs'},
    ...(route && !notFound ? [{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Úvod',item:s.origin+'/'},{'@type':'ListItem',position:2,name:label,item:canonical}]}] : [])
  ]};
  return `<!doctype html>
<html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${s.staging || notFound ? 'noindex, follow' : 'index, follow'}"><meta name="theme-color" content="#064E3B"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:locale" content="cs_CZ"><meta property="og:site_name" content="Lucie Krampotová · Masáže Vsetín"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${s.origin}/assets/social.jpg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Ilustrační masážní zátiší v přírodních tónech"><meta name="twitter:card" content="summary_large_image"><link rel="icon" type="image/svg+xml" href="${base}assets/favicon.svg"><link rel="stylesheet" href="${base}assets/style.css"><script src="${base}assets/app.js" defer></script><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body>
<a class="skip-link" href="#obsah">Přeskočit na obsah</a>${s.staging ? '<div class="test-banner">TESTOVACÍ VERZE <span>· Telefon a firemní údaje jsou dočasné.</span></div>' : ''}
<header class="site-header"><div class="wrap header-inner"><a class="brand" href="${link('')}" aria-label="Lucie Krampotová – úvod"><span>Lucie Krampotová</span><small>MASÁŽE & OSOBNÍ PÉČE</small></a><button class="menu-toggle" type="button" aria-controls="navigation" aria-expanded="false">Menu <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Hlavní navigace">${pages.slice(1,8).map(([path,name])=>`<a href="${link(path)}"${route===path && !notFound ? ' aria-current="page"' : ''}>${name}</a>`).join('')}</nav></div></header>
<main id="obsah" tabindex="-1">${route && !notFound ? `<div class="wrap breadcrumb"><a href="${link('')}">Úvod</a><span aria-hidden="true">/</span><span>${label}</span></div>` : ''}${body}</main>
<footer><div class="wrap footer-main"><a class="brand" href="${link('')}"><span>Lucie Krampotová</span><small>MASÁŽE · VSETÍN</small></a><p>22 let zkušeností.<br>Čas věnovaný vašim zádům.</p><div><a href="tel:${s.phoneLink}">${s.phone}</a><p>${s.address}, ${s.city}</p></div></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} Lucie Krampotová</span><span>${s.businessName} · IČO ${s.businessId}${s.staging ? ' · testovací údaje' : ''}</span><a href="${link('soukromi')}">Soukromí a informace o webu</a></div></footer>
<div class="mobile-booking" aria-label="Rychlé objednání"><a href="tel:${s.phoneLink}">Zavolat <span aria-hidden="true">↗</span></a><a href="sms:${s.phoneLink}">Napsat SMS <span aria-hidden="true">↗</span></a></div></body></html>`;
}
for (const page of pages) { const directory=resolve(out,page[0]); mkdirSync(directory,{recursive:true}); writeFileSync(resolve(directory,'index.html'),render(...page)); }
writeFileSync(resolve(out,'404.html'),render('','Nenalezeno','Stránka nenalezena | Lucie Krampotová','Tato stránka nebyla nalezena.',true));
writeFileSync(resolve(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.filter(p=>p[0]!=='soukromi').map(p=>`<url><loc>${s.origin}/${p[0]?p[0]+'/':''}</loc></url>`).join('')}</urlset>\n`);
writeFileSync(resolve(out,'robots.txt'),`User-agent: *\nAllow: /\n\nSitemap: ${s.origin}/sitemap.xml\n`);
writeFileSync(resolve(out,'_headers'),`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n${s.staging?'  X-Robots-Tag: noindex, follow\n':''}`);
console.log('Built 9 pages, 404, sitemap, robots and headers. Staging:',s.staging);
